### ISSUE TITLE
can't run after deno bundle

### ISSUE THREAD

**Issue by FurryWolfX** [Bestulo/deno-cheerio#2]
```
import { cheerio } from "https://deno.land/x/cheerio@1.0.3/mod.ts";

const $ = cheerio.load(`<div>123</div>`);
const text = $("div").text();
console.log(text);
```

no problem when run it directly. but can't run after deno bundle

```
error: Uncaught ReferenceError: Cannot access '_attributesDewDew2' before initialization
        _attributesDewDew2(),
```

**Comment by Bestulo** [comment]
That problem is due to Deno compatibility with JSPM. Perhaps bundling is buggy. I haven't been able to get it to work with many modules. My suggestion is to try different cdns, equivalent to JSPM, until one works, and then we can switch to that one if it works just as well and allows bundling.

I'm a bit full of work to debug this month. If you have an improved version, please don't hesitate to make a PR. 

Be aware, though, that each CDN will call their things differently, so the Index file will need different variable names.
