### ISSUE TITLE
Huge bundle

### ISSUE THREAD

**Issue by ghost** [Bestulo/deno-cheerio#4]
Hey,

when I bundle cheerio i get a 1.1MB big file (500kb when minified). Thats just too big. When i do a plain npm install of cheerio and check the filesize its 1.9MB also. Did cheerio get out of hand that fast or does something get bundled with i can avoid somehow? I tried to bundle cheerio itself with node, but thats not working. I need cheerio on every http request and since it runs in a worker it gets completely reloaded everytime. It gets so slow that its no longer an option. Maybe you have any ideas @Bestulo ?

**Comment by Bestulo** [comment]
Dunno, maybe don't use that worker? I don't personally have such a problem because I don't bundle things every run. I just made a quick type port, not really too familiar with the module's inner workings. Can't help here. Maybe ask somewhere else. You can close the issue if you want or propose an improvement (PRs are welcome).

**Comment by Bestulo** [comment]
stale
